/*
 * MTIMER_Config.h
 *
 *  Created on: Oct 28, 2022
 *      Author: DELL
 */

#ifndef MCAL_MTIMER_MTIMER_CONFIG_H_
#define MCAL_MTIMER_MTIMER_CONFIG_H_

#include "MTIMER_Private.h"

/*
 * Options for TIMER_MODE
 * 1-TIMER_NORMAL_MODE
 * 2-TIMER_PWM_PHASE_CORRECT_MODE
 * 3-TIMER_CTC_MODE
 * 4-TIMER_FAST_CORRECT_MODE
 */

#define TIMER0_MODE TIMER_NORMAL_MODE

/*
 * Options for OC0 Pin:
 * 1-OC0_PIN_DISCONNECTED
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEARED
 * 4-OC0_PIN_SET
 */

#define  TIMER0_OC0_MODE OC0_PIN_DISCONNECTED

/*
 * Options for CLOCK Pin:
 * 1-NO_CLOCK
 * 2-SYSTEM_CLOCK
 * 3-PRESCALAR_OVER_8
 * 4-PRESCALAR_OVER_64
 * 5-PRESCALAR_OVER_256
 * 6-PRESCALAR_OVER_1024
 * 7-EXTERNAL_CLOCK_FALLING_EDGE
 * 8-EXTERNAL_CLOCK_RISING_EDGE
 */

#define  TIMER0_CLOCK_SCOURCE PRESCALAR_OVER_1024

/*
 * Options for TOV0F Interrupt:
 * 1-NORMAL_MODE_OVERFLOW_ENABLED
 * 2-NORMAL_MODE_OVERFLOW_DISABLED
 */

#define TIMER0_NORMAL_MODE_INTERRUPT_STATE NORMAL_MODE_INTERRUPT_ENABLED

/*
 * Options for OCF0 Interrupt:
 * 1-CTC_MODE_OVERFLOW_ENABLED
 * 2-CTC_MODE_OVERFLOW_DISABLED
 */

#define TIMER0_CTC_INTERRUPT_STATE CTC_MODE_OVERFLOW_DISABLED


/*
 * Options For Fast PWM
 * 1-FAST_PWM_OC0_DISCONNECTED
 * 1-FAST_PWM_OC0_NON_INVERTING
 * 1-FAST_PWM_OC0_INVERTING
 */

#define TIMER0_FAST_PWM_WAVE_MODE FAST_PWM_OC0_NON_INVERTING

/*
 * Options For Phase Correct PWM
 * 1-PHASE_CORRECT_PWM_OC0_DISCONNECTED
 * 1-PHASE_CORRECT_PWM_OC0_NON_INVERTING
 * 1-PHASE_CORRECT_PWM_OC0_INVERTING
 */

#define TIMER0_PHASE_CORRECT_PWM_WAVE_MODE PHASE_CORRECT_PWM_OC0_NON_INVERTING

#endif /* MCAL_MTIMER_MTIMER_CONFIG_H_ */
