/*
 * MSPI_Program.c
 *
 *  Created on: Nov 26, 2022
 *      Author: DELL
 */
#include "MSPI_Interface.h"
#include "MSPI_Config.h"

void MSPI_MasterInit()
{

#if MSPI_DORD_MODE==MSPI_DORD_MSB_FIRST
	CLR_BIT(SPCR,5);
#elif MSPI_DORD_MODE==MSPI_DORD_LSB_FIRST
	SET_BIT(SPCR,5);
#endif

#if MSPI_POLARITY_MODE==MSPI_POL_ACTIVE_HIGH
	CLR_BIT(SPCR,3);
#elif MSPI_POLARITY_MODE==MSPI_POL_ACTIVE_LOW
	SET_BIT(SPCR,3);
#endif


#if MSPI_PHASE_MODE==MSPI_PHASE_SAMPLE_AT_LEADING
	CLR_BIT(SPCR,2);
#elif MSPI_PHASE_MODE==MSPI_PHASE_SAMPLE_AT_TRAILING
	SET_BIT(SPCR,2);
#endif


#if MSPI_INTERRUPT_MODE_MODE==MSPI_INTERRUPT_OFF
	CLR_BIT(SPCR,7);
#elif MSPI_INTERRUPT_MODE_MODE==MSPI_INTERRUPT_ON
	SET_BIT(SPCR,7);
#endif

#if MSPI_CLOCK_MODE_MODE==MSPI_CLOCK_FCPU_4
	CLR_BIT(SPCR,0);
	CLR_BIT(SPCR,1);
	CLR_BIT(SPSR,7);
#elif MSPI_CLOCK_MODE_MODE==MSPI_CLOCK_FCPU_16
	SET_BIT(SPCR,0);
	CLR_BIT(SPCR,1);
	CLR_BIT(SPSR,7);
#elif MSPI_CLOCK_MODE_MODE==MSPI_CLOCK_FCPU_64
	CLR_BIT(SPCR,0);
	SET_BIT(SPCR,1);
	CLR_BIT(SPSR,7);
#elif MSPI_CLOCK_MODE_MODE==MSPI_CLOCK_FCPU_128
	SET_BIT(SPCR,0);
	SET_BIT(SPCR,1);
	CLR_BIT(SPSR,7);
#elif MSPI_CLOCK_MODE_MODE==MSPI_CLOCK_FCPU_2
	CLR_BIT(SPCR,0);
	CLR_BIT(SPCR,1);
	SET_BIT(SPSR,7);
#elif MSPI_CLOCK_MODE_MODE==MSPI_CLOCK_FCPU_8
	SET_BIT(SPCR,0);
	CLR_BIT(SPCR,1);
	SET_BIT(SPSR,7);
#elif MSPI_CLOCK_MODE_MODE==MSPI_CLOCK_FCPU_32
	CLR_BIT(SPCR,0);
	SET_BIT(SPCR,1);
	SET_BIT(SPSR,7);
#endif

//init master spi
SET_BIT(SPCR,4);

//ENABLE SPI
SET_BIT(SPCR,6);

}


void MSPI_SlaveInit()
{
#if MSPI_DORD_MODE==MSPI_DORD_MSB_FIRST
	CLR_BIT(SPCR,5);
#elif MSPI_DORD_MODE==MSPI_DORD_LSB_FIRST
	SET_BIT(SPCR,5);
#endif

#if MSPI_POLARITY_MODE==MSPI_POL_ACTIVE_HIGH
	CLR_BIT(SPCR,3);
#elif MSPI_POLARITY_MODE==MSPI_POL_ACTIVE_LOW
	SET_BIT(SPCR,3);
#endif


#if MSPI_PHASE_MODE==MSPI_PHASE_SAMPLE_AT_LEADING
	CLR_BIT(SPCR,2);
#elif MSPI_PHASE_MODE==MSPI_PHASE_SAMPLE_AT_TRAILING
	SET_BIT(SPCR,2);
#endif


#if MSPI_INTERRUPT_MODE_MODE==MSPI_INTERRUPT_OFF
	CLR_BIT(SPCR,7);
#elif MSPI_INTERRUPT_MODE_MODE==MSPI_INTERRUPT_ON
	SET_BIT(SPCR,7);
#endif

	//init slave spi
	CLR_BIT(SPCR,4);

	//ENABLE SPI
	SET_BIT(SPCR,6);

}

u8 MSPI_SendReceive(u8 Copy_u8TransmittedValue)
{
	SPDR = Copy_u8TransmittedValue;
	//Poll On SPIF Flag
	while(GET_BIT(SPSR,7)==0);

	return SPDR;
}
